apiAuth:
  telegram: '' # Telegram bot token
  twitter: # Twitter bot token
    appKey: ''
    appSecret: ''
    accessToken: ''
    accessSecret: ''
  instagram: # Instagram account
    username: ''
    password: ''

quakeDataAPI: 'https://data.bmkg.go.id/DataMKG/TEWS/autogempa.json'
syncQuakeData: 30 #in second, '0' for brute syncronize | 30 second for performance